bqn-interactive: abstract constants repl functions
AndersonTorres/bqn-mode pull request #7
Opened 2021-10-29 03:38 UTC by doyougnu

Hello,

This looks like a cool language so I thought I would contribute. This PR does the follow:

1. abstract constants out to `defcustom` so users can override them if desired
2. add a bunch of convenience functions for interacting with the `BQN` repl
3. adds `autoload` to `bqn-run`

Please let me know if any edits are necessary.

2021-10-29 19:14 UTC, doyougnu commented on bqn-interactive.el
> +(defcustom bqn--process-name "BQN"
Totally agree, in fact I think it is a mistake to use `defcustom` here, this is the emacs process name for the bqn process so I think it should be implied to be private via double-dash. Resolved in cd4262e841cf7f5e579ac17fe33de3f817a1f4d7

2021-10-29 19:18 UTC, doyougnu commented on bqn-interactive.el
> +(defun bqn-process-execute-region-and-follow (start end &optional dont-follow)
Great points. Thank you for the review.  Resolved in 0e5d580.

I've left `bqn-process-execute-line-and-follow` and `bqn-process-execute-buffer-and-follow` as is, and removed `bqn-process-execute-region-and-follow`, please let me know if any further revision is necessary. I'm happy to contribute

2021-10-29 19:19 UTC, doyougnu commented on bqn-interactive.el
> +(defun bqn-process-execute-region (start end)
See my comments here: https://github.com/AndersonTorres/bqn-mode/pull/7#discussion_r739479004

2021-10-30 04:13 UTC, AndersonTorres requested changes

2021-10-30 04:13 UTC, AndersonTorres commented on bqn-interactive.el
> +   non-nil maintain focus on buffer function was called from."
```suggestion
  "Send the current region to the bqn-process-session.
When DONT-FOLLOW is non-nil, maintain focus on the buffer where the function was called from."
```

In Elisp docstrings, the variables are cited in CAPSLOCK.

https://www.emacswiki.org/emacs/DocString

2021-10-31 13:15 UTC, merged