Draft: Add eldoc and simple documentation lookup to bqn-mode
AndersonTorres/bqn-mode pull request #8
Opened 2021-11-02 01:17 UTC by doyougnu

This PR:
1. Adds the files `bqn-symbols-doc.el` and `bqn-help.el`.
2. `bqn-help.el` provides a major mode for documentation and interactive functions using data set in `bqn-symbols-doc.el`. The most important function is the interactive function `bqn-help-symbol-info-at-point`.
3. Adds `eldoc` support to `bqn-mode` in `bqn-mode.el` using the functions defined in `bqn-help.el`. This simply ties `eldoc-documentation-function` to `bqn-help--eldoc`.

I title this PR as `Draft` because I was hoping for your thoughts since merging brings extra maintenance cost. In particular, I mimic the `eldoc` setup from [gnu-apl-mode](https://github.com/lokedhs/gnu-apl-mode) which uses a constant `alist` to associate symbols to a 3-element list of a short docstring, long docstring, and extra docstring. Rather than use an `alist` I use a hash-map and a vector for better throughput, but maintain the overall design.

The advantages of this setup is lower throughput (marginally so, but having a slow eldoc is a great way to turn people away form emacs), and a more simple design than parsing the markdown in the `doc` subdirectory of the BQN source.

The downside is an extra maintenance burden, and added risk that the docstrings written in `bqn-symbols-doc.el` become out of sync with the current language version. However, I did not see a way to query the bqn interpreter for any documentation and so hard coding the docstrings makes sense to me until this feature is added. At which time it would probably make sense to re-evaluate this strategy.

In any case, comments appreciated. If this design looks fine than until the language becomes more mature then I'll submit more docstrings as I continue to go through the tutorials and bqn docs.

2021-11-10 01:41 UTC, AndersonTorres commented on bqn-symbols-doc.el
> +  Can be applied to characters."
Only characters or other data types too?
Even if it looks obvious, it is be fine to list all possibilities here.

2021-11-10 01:45 UTC, AndersonTorres requested changes

2021-11-10 01:45 UTC, AndersonTorres commented on bqn-symbols-doc.el
> +  To compute a logrithm use Undo: ×⁼ (\\=\\3)"]
```suggestion
  To compute a logarithm use Undo: ×⁼ (\\=\\3)"]
```

Just o be sure, logarithms in which base? `10`, `2` or `e`?

2021-11-11 18:34 UTC, doyougnu commented on bqn-symbols-doc.el
> +  To compute a logrithm use Undo: ×⁼ (\\=\\3)"]
Great catch, this docstring was actually wrong, it pointed to `\=` rather than `\+` for the logarithm. 

> Just o be sure, logarithms in which base? 10, 2 or e?

The left argument (`\w`) determines the base. I've added some examples in the docstring in 33061a4

2021-11-11 19:00 UTC, doyougnu commented on bqn-symbols-doc.el
> +  Can be applied to characters."
Good idea. I've added clarification and an addition example in https://github.com/AndersonTorres/bqn-mode/pull/8/commits/ed6ed1eb095511cd73601f2faf89d1b7da4ac760

2021-11-11 19:46 UTC, AndersonTorres commented on bqn-symbols-doc.el
> +  To compute a logrithm use Undo: ×⁼ (\\=\\3)"]
It does not have the unary/monadic version? Or better, what is the behavior when monadic is used?

2021-11-11 19:47 UTC, AndersonTorres requested changes

2021-11-11 19:47 UTC, AndersonTorres commented on bqn-symbols-doc.el
> +    ⋆⁼ 1      => 0
Well, `log(1)` is 0 in any base. Therefore this example, although useful, says nothing about the default basis.

2021-11-11 19:48 UTC, AndersonTorres commented
When finished, please @ me and/or remove the draft tag.

2021-11-11 21:53 UTC, doyougnu commented on bqn-symbols-doc.el
> +    ⋆⁼ 1      => 0
Oof good point. I've pushed https://github.com/AndersonTorres/bqn-mode/pull/8/commits/944ba4d7c352cbd4af8ef99a796c8ba70dfc6e9b to make clear the base when used monadically is `e`. So now this example becomes `⋆⁼ ⋆1 => 1` which is an identity of natural logs.

2021-11-11 21:54 UTC, doyougnu commented on bqn-symbols-doc.el
> +  To compute a logrithm use Undo: ×⁼ (\\=\\3)"]
Resolved: https://github.com/AndersonTorres/bqn-mode/pull/8/commits/944ba4d7c352cbd4af8ef99a796c8ba70dfc6e9b

2021-11-11 22:00 UTC, doyougnu commented
@AndersonTorres I've clarified the logarithm examples. Thank you for the code review and your comments, I think this PR is much improved because of them. I'm marking this ready for review. 

I think this is a good time to merge what we have and then iteratively add more docs. My plan is to continue adding documentation for the [primitives](https://github.com/mlochbaum/BQN/blob/master/doc/primitive.md).

2021-11-12 00:12 UTC, AndersonTorres requested changes

2021-11-12 00:12 UTC, AndersonTorres commented on bqn-mode.el
>  (require 'bqn-interactive)
I have changed it to `bqn-comint`.
But, to the point, is `bqn-comint` needed to run eldoc? IIRC the help functionality is mostly independent, it should not even rely on a locally installed BQN.

2021-11-12 05:07 UTC, doyougnu commented on bqn-mode.el
>  (require 'bqn-interactive)
You're right, `bqn-comint` is not needed for eldoc; the only thing that ties `bqn-help` to `eldoc` is the line:
```
(setq-local eldoc-documentation-function 'bqn-help--eldoc)
```
in `bqn-mode.el` everything else is independent and does not depend on the local BQN installation.

But I'm confused about the comment. `bqn-help.el` doesn't depend on `bqn-comint` but `bqn-mode` sure does. In any case I've rebased the branch on top of the most recent master so it should be able to merge now.

2021-11-12 17:21 UTC, AndersonTorres commented on bqn-mode.el
>  (require 'bqn-interactive)
In other words bqn-help does not need to call bqn-comint, while the reverse is true.

2021-11-12 18:02 UTC, doyougnu commented on bqn-mode.el
>  (require 'bqn-interactive)
No `bqn-comint` doesn't depend on anything in `bqn-help`. `bqn-comint` just handles and manages the child `*BQN*` process. If the `*BQN*` process was able to return documentation via some primitive like `help(thing)` in python or `:info`/`:type` in Haskell then `bqn-help` could issue that command to the `*BQN*` process via `comint`, then format the return string and show it in the minibuffer or in a doc minor mode. But I didn't see anyway to issue such a command to the `BQN` interpreter so `bqn-help` only looks up information from `bqn-symbols-doc` and provides `(interactive)` functions to lookup that information which are completely decoupled from `bqn-comint`.  So there is no relationship between the `comint` process and the documentation minor mode in `bqn-help`.

2021-11-12 18:45 UTC, AndersonTorres requested changes

2021-11-12 19:17 UTC, doyougnu commented on bqn-help.el
> +(defun bqn-help-symbol-is-called ()
Resolved: https://github.com/AndersonTorres/bqn-mode/pull/8/commits/c9fdf6b1cf0b09b3c935c04f50acfdd2cf9bd69a

2021-11-12 20:34 UTC, AndersonTorres commented on bqn-mode.el
>  (require 'bqn-interactive)
Even better.

2021-11-12 22:27 UTC, merged